version: "3"
services:
  hub:
    image: selenium/hub:3.14
    ports:
      - "4444:4444"
    environment:
      - GRID_BROWSER_TIMEOUT=30
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '1gb'
    volumes:
      - "/dev/shm:/dev/shm"
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module:
    image: shintokg/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=Chrome
      - HUB_HOST=hub
      - MODULE=searchModule.xml
    volumes:
      - ./search-result:/usr/share/udemy/test-
  search-module1:
    image: shintokg/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=searchModule.xml
    volumes:
      - ./search-result1:/usr/share/udemy/test-output
  bookflight_module:
    image: shintokg/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=Chrome
      - HUB_HOST=hub
      - MODULE=bookflight_module.xml
    volumes:
      - ./book-result:/usr/share/udemy/test-output
  bookflight_module1:
    image: shintokg/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=bookflight_module.xml
    volumes:
      - ./book-result1:/usr/share/udemy/test-output
